/* Is the published page the one the parts make?
 *
 *   node check-build.mjs
 *
 * index.html is generated by build.sh but committed, because the tool is meant
 * to be opened straight from the repo. That means two copies of the truth. This
 * fails when they disagree — whether a part was edited without rebuilding, or
 * the page itself was edited and is about to be overwritten.
 */
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const PARTS = ['01-head.html', '02-body.html', '03-core.js', '04-ui.js'];

const made = PARTS.map(f => readFileSync(join(here, 'build', f), 'utf8')).join('');
const published = readFileSync(join(here, 'index.html'), 'utf8');

if (made === published) {
  /* counted the way build.sh counts, so the two agree */
  const lines = published.split('\n').length - (published.endsWith('\n') ? 1 : 0);
  console.log(`ok   index.html is the ${PARTS.length} parts, ${lines} lines`);
  process.exit(0);
}

/* say where they part company, so the fix is obvious */
const a = made.split('\n'), b = published.split('\n');
let line = 0;
while (line < a.length && line < b.length && a[line] === b[line]) line++;
console.error('FAIL index.html is not what build/ makes.');
console.error(`     first difference at line ${line + 1}:`);
console.error(`     build/    ${JSON.stringify((a[line] || '<end of file>').slice(0, 90))}`);
console.error(`     index.html ${JSON.stringify((b[line] || '<end of file>').slice(0, 90))}`);
console.error(`     ${a.length} lines from the parts, ${b.length} in the page.`);
console.error('     Run ./build.sh and commit index.html, or put your edit in build/ instead.');
process.exit(1);
